import Foundation
import os.log

/// Adapter for applying Cloudflare credentials to the system environment and Wrangler CLI
@MainActor @preconcurrency
final class CloudflareAdapter {
    private static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "GreatDeploy", category: "CloudflareAdapter")
    
    static let shared = CloudflareAdapter()
    
    private init() {}
    
    /// Applies the Cloudflare token and account ID to the system
    /// - Parameters:
    ///   - token: The Cloudflare API Token
    ///   - accountId: The Cloudflare Account ID
    func applyToken(_ token: String, accountId: String) async throws {
        // 1. Update macOS GUI environment variables via launchctl
        try await updateLaunchctlEnvironment(token: token, accountId: accountId)
        
        // 2. Update Wrangler configuration file
        try await updateWranglerConfig(token: token, accountId: accountId)
    }
    
    /// Clear all Cloudflare credentials
    func clearCredentials() async throws {
        try await applyToken("", accountId: "")
    }
    
    private func updateLaunchctlEnvironment(token: String, accountId: String) async throws {
        let setenvPath = "/bin/launchctl"
        
        // Token
        let tokenProcess = Process()
        tokenProcess.executableURL = URL(fileURLWithPath: setenvPath)
        if token.isEmpty {
            tokenProcess.arguments = ["unsetenv", "CLOUDFLARE_API_TOKEN"]
        } else {
            tokenProcess.arguments = ["setenv", "CLOUDFLARE_API_TOKEN", token]
        }
        try tokenProcess.run()
        tokenProcess.waitUntilExit()
        
        // Account ID
        let accountProcess = Process()
        accountProcess.executableURL = URL(fileURLWithPath: setenvPath)
        if accountId.isEmpty {
            accountProcess.arguments = ["unsetenv", "CLOUDFLARE_ACCOUNT_ID"]
        } else {
            accountProcess.arguments = ["setenv", "CLOUDFLARE_ACCOUNT_ID", accountId]
        }
        try accountProcess.run()
        accountProcess.waitUntilExit()
    }
    
    private func updateWranglerConfig(token: String, accountId: String) async throws {
        let fileManager = FileManager.default
        let homeDir = fileManager.homeDirectoryForCurrentUser
        let configPaths = [
            homeDir.appendingPathComponent(".wrangler/config", isDirectory: true),
            homeDir.appendingPathComponent(".config/.wrangler/config", isDirectory: true)
        ]
        
        // Ensure default location exists
        let primaryConfigDir = configPaths[0]
        if !fileManager.fileExists(atPath: primaryConfigDir.path) {
            try fileManager.createDirectory(at: primaryConfigDir, withIntermediateDirectories: true, attributes: nil)
        }
        
        let configFile = primaryConfigDir.appendingPathComponent("default.toml")
        
        if token.isEmpty {
            if fileManager.fileExists(atPath: configFile.path) {
                try fileManager.removeItem(at: configFile)
            }
        } else {
            let content = """
            # Generated by GreatDeploy
            api_token = "\(token)"
            account_id = "\(accountId)"
            """
            try content.write(to: configFile, atomically: true, encoding: .utf8)
        }
    }
}
