import Foundation
import os.log

/// Adapter for applying Cloudflare credentials to the system environment and Wrangler CLI
final class CloudflareAdapter: CloudflareAdapting {
    private static let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "GreatDeploy", category: "CloudflareAdapter")

    static let shared = CloudflareAdapter()

    private let homeDirectory: URL
    private let processRunner: ProcessRunner
    private let fileSystem: FileSystem
    private let launchctlRunner: ((String, [String]) throws -> Void)?
    private let launchctlEnvironmentReader: ((String) -> String?)?

    init(
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser,
        processRunner: ProcessRunner = MacProcessRunner.shared,
        fileSystem: FileSystem = MacFileSystem.shared,
        launchctlRunner: ((String, [String]) throws -> Void)? = nil,
        launchctlEnvironmentReader: ((String) -> String?)? = nil
    ) {
        self.homeDirectory = homeDirectory
        self.processRunner = processRunner
        self.fileSystem = fileSystem
        self.launchctlRunner = launchctlRunner
        self.launchctlEnvironmentReader = launchctlEnvironmentReader
    }
    
    /// Applies the Cloudflare token and account ID to the system
    /// - Parameters:
    ///   - token: The Cloudflare API Token
    ///   - accountId: The Cloudflare Account ID
    ///   - syncWranglerConfig: When true, also writes/removes Wrangler's plaintext config file.
    func applyToken(_ token: String, accountId: String, syncWranglerConfig: Bool = false) async throws {
        try await Task.detached(priority: .userInitiated) {
            // 1. Update macOS GUI environment variables via launchctl.
            try await self.updateLaunchctlEnvironment(token: token, accountId: accountId)

            // 2. Wrangler config is plaintext, so keep it explicit opt-in only.
            if syncWranglerConfig {
                try self.updateWranglerConfig(token: token, accountId: accountId)
            }
        }.value
    }
    
    /// Clear all Cloudflare credentials
    func clearCredentials(syncWranglerConfig: Bool = false) async throws {
        try await applyToken("", accountId: "", syncWranglerConfig: syncWranglerConfig)
    }

    /// Reads the Cloudflare account ID visible to GUI apps via launchctl.
    func currentAccountId() async -> String? {
        if let launchctlEnvironmentReader {
            return launchctlEnvironmentReader("CLOUDFLARE_ACCOUNT_ID")
        }

        do {
            let result = try await processRunner.run(
                executable: URL(fileURLWithPath: "/bin/launchctl"),
                arguments: ["getenv", "CLOUDFLARE_ACCOUNT_ID"],
                timeout: 5
            )
            guard result.exitCode == 0, !result.stdout.isEmpty else {
                return nil
            }
            return result.stdout
        } catch {
            return nil
        }
    }

    private func updateLaunchctlEnvironment(token: String, accountId: String) async throws {
        try await runLaunchctl(
            executablePath: "/bin/launchctl",
            arguments: token.isEmpty
                ? ["unsetenv", "CLOUDFLARE_API_TOKEN"]
                : ["setenv", "CLOUDFLARE_API_TOKEN", token]
        )

        try await runLaunchctl(
            executablePath: "/bin/launchctl",
            arguments: accountId.isEmpty
                ? ["unsetenv", "CLOUDFLARE_ACCOUNT_ID"]
                : ["setenv", "CLOUDFLARE_ACCOUNT_ID", accountId]
        )
    }

    private func runLaunchctl(executablePath: String, arguments: [String]) async throws {
        if let launchctlRunner {
            try launchctlRunner(executablePath, arguments)
            return
        }

        let result = try await processRunner.run(
            executable: URL(fileURLWithPath: executablePath),
            arguments: arguments,
            timeout: 10
        )
        guard result.exitCode == 0 else {
            throw CloudflareAdapterError.commandFailed
        }
    }

    private func updateWranglerConfig(token: String, accountId: String) throws {
        let primaryConfigDir = homeDirectory.appendingPathComponent(".wrangler/config", isDirectory: true)
        if !fileSystem.exists(primaryConfigDir) {
            try fileSystem.createDirectory(at: primaryConfigDir)
        }

        let configFile = primaryConfigDir.appendingPathComponent("default.toml")

        if token.isEmpty {
            if fileSystem.exists(configFile) {
                try? FileManager.default.removeItem(at: configFile)
            }
        } else {
            let content = """
            # Generated by GreatDeploy
            api_token = "\(Self.escapeTomlString(token))"
            account_id = "\(Self.escapeTomlString(accountId))"
            """
            guard let data = content.data(using: .utf8) else {
                throw CloudflareAdapterError.encodingFailed
            }
            try fileSystem.atomicWrite(data, to: configFile)
            try? FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: configFile.path)
        }
    }

    static func escapeTomlString(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
            .replacingOccurrences(of: "\t", with: "\\t")
    }

    enum CloudflareAdapterError: LocalizedError {
        case commandFailed
        case encodingFailed
        case processTimeout

        var errorDescription: String? {
            switch self {
            case .commandFailed:
                return "Cloudflare environment update failed"
            case .encodingFailed:
                return "Cloudflare config encoding failed"
            case .processTimeout:
                return "Cloudflare environment update timed out"
            }
        }
    }
}
